package org.flowableSpringboot.bootstrap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ApplicationDataRepository applicationDataRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public void addNewUser () {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		ApplicationData application = new ApplicationData("saurabh",
				"saurabh@kuliza.com", "0003434343");
		System.out.println("...................This is test 1="+application);
		System.out.println("...................This is test 2="+applicationDataRepository);
		applicationDataRepository.save(application);
		System.out.println("...................This is test ");
	}

	
}